04-skeleton-commit1
js-tasks-ru/htmlcss-20210513_achegevara pull request #11
Opened 2021-05-24 15:23 UTC by achegevara

Попробовал сделать с учётом твоих рекомендаций - вроде получилось. По крайней мере, визуально и технически(отступы, размеры) как в макете. Но возможно, средства достижения цели были не те) В таком случае буду рад замечаниям, чтобы приступить к доработке ;D

2021-05-24 15:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-26 22:06 UTC, GSemikozov requested changes

2021-05-26 22:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.container {
это нужно вынести в тег style страницы решения, поскольку - не относится к блоку "skeleton"

2021-05-26 22:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +margin: 24px 40px 32px 24px;
лучше вместо марджина здесь использовать паддинг с такими же значениями у родителя

2021-05-26 22:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__ellipse {
скорее circle)

2021-05-26 22:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__not-full-lines-container {
.skeleton__not-full-lines-container -> .skeleton__container

2021-05-26 22:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +width: 257px;
лучше все-таки чтобы ширина была относительной, можно в процентах либо растянуть с помощью flex-grow

2021-05-26 22:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +width: 515px;
то же самое что и выше

2021-05-27 08:52 UTC, achegevara commented on 04-lection2/02-skeleton/skeleton.css
> +.container {
Пересмотрел с учётом всех комментариев - поменял стили так, что min- и max-width назначил на блок skeleton.
max-width: 515px;
min-width: min-content;

Конкретных требований по размерам не было, поэтому max задал, как в макете. Но с учётом изменений размеров на относительные(в %), будет работать с любыми размерами. Появятся требования к min/max - поменяем быстро!
Т.к. позиционирование самого скелетона на странице задачи не важно, класс container остался для этих целей(пока пустой).

2021-05-27 08:52 UTC, achegevara commented on 04-lection2/02-skeleton/skeleton.css
> +margin: 24px 40px 32px 24px;
Готово!

2021-05-27 08:52 UTC, achegevara commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__ellipse {
В макете был ellipse, но поменял, не вопрос))

2021-05-27 08:53 UTC, achegevara commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__not-full-lines-container {
И здесь Заменил.

2021-05-27 08:55 UTC, achegevara commented on 04-lection2/02-skeleton/skeleton.css
> +width: 257px;
Сделал в %, изменил размеры родительских контейнеров на своё усмотрение. Подробнее в ответе на первый вопрос описал.

2021-05-27 08:56 UTC, achegevara commented on 04-lection2/02-skeleton/skeleton.css
> +width: 515px;
Сделал в %, изменил размеры родительских контейнеров на своё усмотрение. Подробнее в ответе на первый вопрос описал.

2021-05-28 15:46 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.container {
окей! мы как раз недавно прошли тему по адаптивности - надеюсь, теперь стало понятнее, почему не стоит задавать фиксированные размеры)

2021-05-28 15:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__ellipse {
видимо, ошибка дизайнера)

2021-05-28 15:50 UTC, GSemikozov approved these changes

2021-05-28 15:50 UTC, merged