06-avatar-initial-commit
js-tasks-ru/htmlcss-20210513_achegevara pull request #15
Opened 2021-05-30 18:15 UTC by achegevara

Уточнил нюансы в лс. Должно быть хорошо выполнено.

2021-05-30 18:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-01 09:05 UTC, GSemikozov requested changes

2021-06-01 09:05 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +html {
переменные вешать на html глобально не стоит, поскольку они касаются только аватара. Поэтому - их можно определить в рут классе блока - .avatar.
кстати, верстка сделана не по БЭМ, надо бы переделать. Root классом будет .avatar, модификаторы - .avatar_small etc, а сама картинка это элемент нашего блока .avatar - .avatar__img

2021-06-01 19:42 UTC, achegevara commented on 06-lection4/01-avatar/avatar.css
> +html {
Всё сделал!

2021-06-02 06:36 UTC, GSemikozov approved these changes

2021-06-02 06:36 UTC, merged