06-srcset-initial-commit
js-tasks-ru/htmlcss-20210513_achegevara pull request #17
Opened 2021-05-30 18:18 UTC by achegevara

Тоже вроде как мини-задачка. Считаю, что выполнил.

2021-05-30 18:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-01 09:00 UTC, GSemikozov requested changes

2021-06-01 09:00 UTC, GSemikozov commented on 06-lection4/03-srcset/srcset.css
> +object-fit: contain;
лучше все-таки cover - так мы точно будет уверены в том что картинки разных пропорций четко встроятся в круг

2021-06-01 19:39 UTC, achegevara commented on 06-lection4/03-srcset/srcset.css
> +object-fit: contain;
Готово! Я сразу не совсем правильно понял условие "вписать картинку") Если прям чтоб всю область заняла, жертвуя частью контента, то определённо согласен.

2021-06-02 06:36 UTC, GSemikozov approved these changes

2021-06-02 06:37 UTC, merged