05-tooltip-initial-commit
js-tasks-ru/htmlcss-20210513_achegevara pull request #20
Opened 2021-06-02 17:26 UTC by achegevara

Делал как в макете, вроде получилось. Но как обычно готов к замечаниям и улучшениям)

2021-06-02 17:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-05 18:58 UTC, GSemikozov requested changes

2021-06-05 18:58 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
снова эти злосчастные стили не относящиеся к блоку, а добавленные для определения внешнего поведения компонента)) на самом деле внешнее поведение мы определяем через родителя, через миксы, по поскольку в данном случае стили на body добавлены лишь для того чтобы отобразить более красиво пример решения - эту часть нужно перенести в тег style html с решением

2021-06-06 08:02 UTC, achegevara commented on 05-lection3/01-tooltip/tooltip.css
> +body {
Мне уже даже стыдно) И правда что-то зачастил с этими ошибками. Перенёс!

2021-06-08 11:57 UTC, GSemikozov approved these changes

2021-06-08 11:58 UTC, merged