09-burger-task
js-tasks-ru/htmlcss-20210513_achegevara pull request #29
Opened 2021-06-13 07:08 UTC by achegevara

Сделал как в макете + учитывая разбор на лекции.

- Стили делал отдельно от основного меню, т.к. достаточно много изменений, да и предыдущий ПР ещё не вмерджен)
- Стили на тоглер подтянутся после мерджа предыдущего ПРа. Там уже можно будет и ссылки править, и тёмную тему подключать.

2021-06-13 07:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-13 13:54 UTC, GSemikozov requested changes

2021-06-13 13:54 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__components {
может все-таки .burger-menu__menu-wrapper, .burger-menu__menu, .burger-menu__menu-item, .burger-menu__menu-title, .burger-menu__menu-link - вместо тех классов которые ниже? Просто так мне кажется по семантике будет больше понятно к чему относятся те или иные элементы)

2021-06-13 13:54 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.menu__item.active {
.menu__item_active?)

2021-06-14 08:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-14 09:30 UTC, achegevara commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__components {
Согласен, наворотил что-то я =/ Поправил, сейчас намного более читаемо.

2021-06-14 09:30 UTC, achegevara commented on 09-lection7/01-burger-menu/burger-menu.css
> +.menu__item.active {
Да, как и в предыдущем ПРе ошибка) Исправил.

2021-06-14 09:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-15 20:21 UTC, GSemikozov requested changes

2021-06-15 20:21 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-button {
.burger-button => .burger-menu__button

2021-06-15 20:21 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-circle {
.burger-circle -> .burger-menu__circle (только - что за circle? =))

2021-06-15 20:21 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-close {
.burger-menu-close -> .burger-menu__close-btn

2021-06-16 05:28 UTC, achegevara commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-button {
Опять я наименования проглядел( Исправил.

2021-06-16 05:29 UTC, achegevara commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-circle {
Этот тот кружочек под крестиком-закрывашкой)) Переименовал в button-bg, может более понятно.

2021-06-16 05:29 UTC, achegevara commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-close {
Готово!

2021-06-16 05:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-16 06:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-16 08:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-16 08:50 UTC, GSemikozov approved these changes

2021-06-16 08:50 UTC, merged