project-update
js-tasks-ru/htmlcss-20210513_achegevara pull request #32
Opened 2021-06-23 14:34 UTC by achegevara

Добавил превью-карточки и сделал отдельные страницы для скелетона, аккордеона и кнопок. Ну и сопутствующие этому фиксы + мелкие правки в общем по проекту.

2021-06-23 14:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-23 14:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-24 10:24 UTC, GSemikozov requested changes

2021-06-24 10:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-preview-container {
вот эта штука к компоненту Кнопка не относится, надо куда-то унести)

2021-06-24 10:24 UTC, GSemikozov commented on README.md
> -# Задачник для курса по современной вёрстке
удалять readme не обязательно)

2021-06-25 07:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-25 07:54 UTC, achegevara commented on 03-lection1/01-button/button.css
> +.button-preview-container {
Перенёс в card, переименовал соответствующе)

2021-06-25 07:56 UTC, achegevara commented on README.md
> -# Задачник для курса по современной вёрстке
Это я думал русскоязычный текст из форка убрать (как портфолию буду использовать, там всё на англе обычно). Но удаление и в ПР пошло, это не учёл.

2021-06-25 08:04 UTC, GSemikozov commented on README.md
> -# Задачник для курса по современной вёрстке
а, окей

2021-06-25 08:04 UTC, GSemikozov approved these changes

2021-06-25 08:04 UTC, merged