layout
js-tasks-ru/htmlcss-20210513_achegevara pull request #6
Opened 2021-05-19 05:33 UTC by achegevara

Added 
- normalize.css, 
- font "Inter",
- prepared the layout page from our hometask.

2021-05-19 05:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-22 13:21 UTC, GSemikozov requested changes

2021-05-22 13:21 UTC, GSemikozov commented on components/footer/footer.css
> +position: absolute;
когда копируем стили из фигмы - надо делать это осторожно =) в данном случае фиксированные размеры и позиционирование относятлся лишь к самой фигме. Тут и ниже - надо удалить, вместе с комментариями.

2021-05-22 13:21 UTC, GSemikozov commented on components/main/main.css
> +position: absolute;
здесь как и в комменте выше - не нужно этот блок позиционировать абсолютно и жестко задавать фиксированные размеры.

2021-05-23 17:00 UTC, achegevara commented on components/footer/footer.css
> +position: absolute;
Готово!

2021-05-23 17:00 UTC, achegevara commented on components/main/main.css
> +position: absolute;
И это готово)

2021-05-23 17:02 UTC, GSemikozov requested changes

2021-05-23 17:02 UTC, GSemikozov commented on components/footer/footer.css
> +padding-left: 417px;
паддинги здесь не нужно указывать, иначе при уменьшении ширины страницы будет беда - в какой-то появится горизонтальный скрол) а если нужно выровнять по центру - можно просто `margin: 0 auto`

2021-05-23 17:08 UTC, achegevara commented on components/footer/footer.css
> +padding-left: 417px;
Протестил - и правда беда) Поправил.

2021-05-23 17:09 UTC, GSemikozov approved these changes

2021-05-23 17:09 UTC, merged